### ISSUE TITLE
Unable to add to String/Array prototypes

### ISSUE THREAD

**Issue by stewartoallen** [patriksimek/vm2#111]
I'm adding to String.prototype and Array.prototype functions, but these functions are not present in code executed in the VM context.

**Comment by dodekeract** [comment]
@stewartoallen Isn’t this working as intended? The VM shouldn't have access to anything in the parent process.

Also, [you shouldn’t modify native `prototype`s](https://stackoverflow.com/questions/14034180/why-is-extending-native-objects-a-bad-practice).

**Comment by almercier** [comment]
@FlorianWendelborn @patriksimek @stewartoallen 
I think this issue should be reopened. This is a valid issue because it is pretty common and standard practice to add polyfills by modifying native prototypes according to MDN documentation. [For example...](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill)

Because we cannot do this, it will error If for example an array is created within the VM and passed into a proxied function that is expecting those polyfills to exist.

There should at least be an easy way to pass those polyfills proxied into the VM somehow.
