### ISSUE TITLE
Access control regarding access direct FD number

### ISSUE THREAD

**Issue by ehjoon** [patriksimek/vm2#114]
I know that arbitrary FD number could be used in node.js script.
I have a question about whether vm2 can prohibit arbitrary fd access like below.

> Calling fs.read(9, buf, 0, 10, 0, readCB) could read no-allowed file system if FD 9 is opened by other sanbox code or outside of sandbox

**Comment by binki** [comment]
In my understanding of the purpose of vm2, you would avoid this sort of problem by **not allowing the code to access the `fs` module**.

In normal JavaScript, it feels like if you can eliminate all references to the global object and invoke a function through, e.g., `'use strict';` mode, you would have successfully sandboxed the code. However, through various tricks, it is often possible in nodejs to somehow get access to `require()` which would let you bypass everything. The vm2 module tries to block off all those tricks for you and make it easy to pass proxied objects into the sandbox so that, e.g., you could pass a `read()` and `write()` that only accesses the resources you've decided the sandboxed code should be allowed to access.

**Comment by ehjoon** [comment]
I understood fully you mean
