### ISSUE TITLE
Help with the return value of running vm code

### ISSUE THREAD

**Issue by simon-o-matic** [patriksimek/vm2#125]
1. Calling `vm.run(5)` I get `5` as the result.
1. Calling `vm.run({a: 6}) returns `6`.
1. Calling `vm.run({a: 6, b: 7})` results in an error about an unexpected colon.
1. `vm.run({a: {b: 66}})` gives `66` as the result.
1. `vm.run(let f = {a: 5, b: 6}; f)` and I get back the structure `{a: 5, b: 6}` as the result.

Can someone explain whats going on here to me? The middle 3 examples I don't understand. 1 and 5 are the only ones I understand and expected.

Thanks,
Simon.

**Comment by tibuurcio** [comment]
Hi there!

I believe this behaviour has to do with the notion of javascript **expressions** and **statements**.

> Expressions: Any reference to a variable or value, or a set of variable(s) and value(s) combined with operators.

> Statements: made up of one or more expressions

You can learn in depth about it in [Kyle's You Don't Know JS Book 1](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch1.md)

Since vm2 uses Node's VM module, it can only evaluate expressions and statements, just like the browser `window.eval()` function. If you test it in your browser you'll see the same behaviours from 1, 2 and 3 in the console.

You can use an AST explorer tool to find out what's going on, for instance [AST Explorer](https://astexplorer.net/) is a good one.

1. `5` is a valid _ExpressionStatement_

2. The brackets are evaluated as a _BlockStatement_, and the `a: 6` is considered a _LabeledStatement_, which evaluates to `6`, just like 1.

3. Cannot be evaluated because of the comma, since it's not a valid statement nor expression
  3.1 Fun fact: If you wrap the object around parenthesis `vm.run('({a: 6, b: 7})')`, it turns into a valid _ObjectExpression_ and you'll see the expected object output.

4. Same as 2, the brackets are considered _BlockStatement's_ with _LabeledStatement's_ inside, which evaluates to the value of `66`

5. In this case you're evaluating a valid _VariableDeclaration_: `let f = {a: 5, b: 6};`, followed by a valid _ExpressionStatement_: `f`

Hope it has cleared your understanding!
AST's are a fantastic subject and a lot of the javascript we use today are powered by them :)
Cheers!
