### ISSUE TITLE
Use of Isolates

### ISSUE THREAD

**Issue by gabegorelick** [patriksimek/vm2#167]
Lately there's been [some press](https://blog.cloudflare.com/cloud-computing-without-containers/) about using V8's Isolates as a sandboxing mechanism. Perhaps that's something vm2 should leverage instead of Node's native `vm` module? 

https://github.com/laverdet/isolated-vm seems like something that could be interesting.

**Comment by patriksimek** [comment]
I've spent the last few days working with isolated-vm, and while I find it superior concerning multithreading, I'm currently stuck with memory issues due to the cloning of primitives between isolates. I've created a small comparison of vm2 to isolated-vm [here](https://github.com/patriksimek/vm2/wiki/vm2-vs-isolated-vm). I'm still in the process of learning how to use isolated-vm efficiently, so things are subject to change.

Anyway, I believe there is space for both libraries. It seems like both doing the same thing, but it's just not that simple, and each can serve different use case better than the other.

**Comment by beeing** [comment]
Recent versions of node includes support for worker threads, which offers better performance compared to cluster (not sure if this applies to isolates).

Quoted from node 11.x documentation:

> Unlike child_process or cluster, worker_threads can share memory. They do so by transferring ArrayBuffer instances or sharing SharedArrayBuffer instances.

This can also be an area to explore.

**Comment by gabegorelick** [comment]
> Recent versions of node includes support for worker threads, which offers better performance compared to cluster (not sure if this applies to isolates).

https://github.com/laverdet/isolated-vm/tree/cf2f95c4715785cbf473870703b2055e7f2ed52a#alternatives does a good job comparing vm2, isolates, worker threads, and a few other solutions.

**Comment by NotWearingPants** [comment]
Electron is planning to drop support for Node.js's vm module (which vm2 relies on) in future versions: https://github.com/electron/electron/pull/26087
(for now its usage prints a warning to the console).
So now might be a good time to re-open the issue and discuss moving forward.
