### ISSUE TITLE
external modules can require files outside of specified root with impunity

### ISSUE THREAD

**Issue by hcldan** [patriksimek/vm2#332]
see #331 

I'm not sure who is using this project or if it's maintained at all... but the comments on the main readme about being secure against all known attacks made be to believe simple things like this would not work.

I have seen issues here about root closed due to it "not being that safe" to allow external and root at the same time... but I'm not really seeing much value in not focusing on this situation.  if you want to run any amount of code that contains modules and has dependencies, you'll need to at some point let them use require to get at them.

**Comment by XmiliaH** [comment]
The problem is that with the wrong configuration this can happen. The option `require.context` needs to be `sandbox` if untrusted modules are required. If this is not set the hosts require is used which is out of our control. Instead of requiring some other module these modules could also expose a function that just runs code supplied from the sandbox in the host environment.
