### ISSUE TITLE
console: 'redirect' doesn't trigger event for all parameters, just first

### ISSUE THREAD

**Issue by mariusa** [patriksimek/vm2#342]
`console: 'inherit'` works fine for
```
console.log('hello', 'world')
```
output: hello world

Using `console: 'redirect'` with
```
    vm.on('console.log', (data) => {
        console.log(`VM stdout: ${data}`)
    })
```
gives only 1st parameter:
```
VM stdout: hello
```
'world' is never received, neither in same call as one big string, nor as a separate event.

**Comment by Aggtaa** [comment]
That's because your callback function accepts only one parameter
```
(data) => {
    console.log(`VM stdout: ${data}`)
}
```

If you want to receive more, you should either pass an array to the console.log call, like
```
console.log(['hello', 'world'])
```
which is not very convenient, 
or add more parameters to the callback, like
```
(data1, data2) => console.log(`VM stdout: ${data1}, ${data2}`)
```
or, in case you cannot predict the exact number of parameters will be passed to console.log, which is absolutely normal and expected, you can write the callback like this
```
(...dataArray) => console.log(`VM stdout: ${dataArray}`)
```
`dataArray` will be of Array type and will contain all arguments passed to console.log.
Also there is a built-in variable called `arguments` in every function that serves similar function and that you don't have to declare explicitly, although `arguments` is not quite an Array, specifically it is missing the `length` property, which can be sometimes inconvenient and lacks this kind of functionality:
```
(data, ...additionalDataArray) => console.log(`VM stdout: ${data}, additional args: ${additionalDataArray}`)

**Comment by mariusa** [comment]
Thanks!
