### ISSUE TITLE
Locking up the host

### ISSUE THREAD

**Issue by CBenni** [patriksimek/vm2#35]
Using promises (or similar async callbacks), one can circumvent the timeouts:

```
var vm = new vm2({
    timeout: 10,
    sandbox: {}
});
vm.run("new Promise((r,j)=>r()).then((v)=>{while(true);})")
```

The `while(true)` code is not time limited at all and will lock up the entire node.js process.
For simplicity, a non-shortened version of the code in the string:

```
new Promise( (resolve, reject) => resolve() )
.then( function(value) {
    while(true);
}
```

Is there some fail safe way to fix/prevent this? Or is this an intrinsic problem of how node.js vm works? Obviously, doing 

```
sandbox: { Promise: null }
```

prevents the user from creating promises, but as long as the user has access to any kind of async code, he can crash the VM.

**Comment by patriksimek** [comment]
Unfortunately, this is how node's VM works and there is nothing I can change about that.

**Comment by derhuerst** [comment]
Hey! I wrote [a module](https://github.com/derhuerst/inspect-code) that makes [really simple async code sync](https://gist.github.com/derhuerst/2a9e08c961b400695b84e983f5b31534#making-asynchronous-js-code-synchronous). I'm interested in expanding it to other stuff like Promises.

Let's join forces on this!

**Comment by nanowizard** [comment]
Would using `Promise: null ` in the sandbox options _guarantee_ that the script cannot add any callbacks to the event loop (assuming, of course, that no other async functionality was added to the sandbox scope)? 

If not, is there another way to force the code to be only synchronous?

**Comment by derhuerst** [comment]
Btw i moved to [lolex](https://github.com/sinonjs/lolex) for all timer-related code (e.g. `setTimeout`). Rewriting async code like I linked above is still possible but tedious.

For `Promise`s, they usually resolve on next tick, so it would be possible to mock them so that we can control this next tick.

**Comment by wysisoft** [comment]
Is this still a problem? I ran the code

const {VM} = require('vm2');
var vm = new VM({
    timeout: 10,
    sandbox: {}
});
vm.run("new Promise((r,j)=>r()).then((v)=>{while(true);})")
console.log('done')

and it completed fine?

**Comment by jtokoph** [comment]
Is there a way to disable promises in the VM?

Using `sandbox: { Promise: null }` causes issues with contextify.

```js
VM = require('vm2').VM;
new VM({
  sandbox: {
    Promise: null,
  }
}).run('class Foo {}; new Foo();');
```
```
TypeError: Right-hand side of 'instanceof' is not an object
    at Object.value (/Users/jtokoph/tmp/node_modules/vm2/lib/contextify.js:232:22)
    at VM.run (/Users/jtokoph/tmp/node_modules/vm2/lib/main.js:207:39)
```

Using `sandbox: { Promise: function() }` causes the process to hang with this simple example:

```js
VM = require('vm2').VM;
new VM({
  sandbox: {
    Promise: function() {},
  }
}).run('class Foo {}; new Foo();');
```

**Comment by patriksimek** [comment]
@jtokoph Please open a separate ticket for this.

**Comment by jdat82** [comment]
Even if we can't prevent `while(true)` loops, setting a memory cap would help. An infinite loop will consume a lot of memory. By adding the possibility to set a threshold for a script, we could mitigate their impact. 

Not being able to detect and/or block infinite loops is a BIG issue because the only thing you can do when that happens is to restart your server which is not really a solution. 

Do you think that would be possible?
