### ISSUE TITLE
new URL not working

### ISSUE THREAD

**Issue by fadomire** [patriksimek/vm2#357]
Hello,

i'm surprised that the following code does not work in vm.run as it runs properly with 'classic' nodejs
```js
const {VM} = require('vm2');
const vm = new VM();

vm.run(`new URL('https://github.com/patriksimek/vm2')`); 
```
it gives following error: ReferenceError [Error]: URL is not defined

i could require('url').URL and then it works, with proper VM options for require, but why it does not work as in nodejs:
```js
new URL('https://github.com/patriksimek/vm2')
```

**Comment by y21** [comment]
For the same reason why `setTimeout`, `setInterval`, `atob`, `btoa`, etc do not work.  `URL` is not part of the JS standard. It's a Web API and implemented by the runtime, in this case Node.js, not by the JS engine. `vm2` (and `vm`) do not give you access to Node.js globals by default (except for `Buffer`) because some of them aren't safe enough to be exposed to untrusted code, i.e. `process` (one can use it to exit the host process)

**Comment by fadomire** [comment]
Thanks for the detailed explanation, perfectly clear.
